-- Supabase database schema migrations go here
-- This file tracks all database changes so they can be versioned with git

-- Example: Create a tasks table for the CFO/Ops agent
-- CREATE TABLE tasks (
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--   user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
--   title TEXT NOT NULL,
--   description TEXT,
--   status TEXT DEFAULT 'pending',
--   created_at TIMESTAMP DEFAULT now(),
--   updated_at TIMESTAMP DEFAULT now()
-- );
